Some R tips
======

R object names can start with a dot (.)
------

```{r}
.x <- c(1,2)
print(.x)

# for a function
.len <- function(x) {
  length(x)
}
.len(c(1,2,3))
```

About namespace in R
------
*TODO: this won't work with knitr (will explore later)*

```{r}
# save the default options
op <- options()
# options() can be used to examine all global options.
getOption("digits")

# :: can be used to access objects in a namespace
# use ::: if the object is not exported (private)
base::.Options$digits

## change digits to 2
# below is a wrong way
base::.Options$digits <- 2

# need to use assignInNamespace function
myOptions <- base::.Options
myOptions$digits <- 2
assignInNamespace(x=".Options", myOptions, ns='base')
base::.Options$digits
x <- 0.123456
# only show 2 digits
x

myOptions$digits <- 5
assignInNamespace(x=".Options",myOptions,ns='base')
base::.Options$digits
# now show 5 digits (with rounding)
x

# change the options back to default
options(op)
# return list
options("digits")
# return value
getOption("digits")
```